# Run with `flutter pub run ffigen --config ffigen.yaml`.
name: SeagortCppBindings
description: |
  Bindings for seagort c++.
output: '../lib/native_cpp_library.dart'
headers:
  entry-points:
    - 'utils/c++/file.h'
  include-directives:
    - 'utils/c++/file.h'
preamble: |
  // Copyright (c) 2024 NIMA. 
  // This package is governed by an MIT License.
  // All Rights Reserved.
comments:
  style: any
  length: full
ffi-native: